chat/urls.py
from django.urls import path

from . import views
from .views import ThreadView
app_name = 'chat'

urlpatterns = [
    
    path('<str:room_name>/', ThreadView.as_view(), name='room'),
]

main/urls.py
from django.urls import path
from main.views import *

from django.conf.urls.static import static
from django.conf import settings
app_name = 'main'

urlpatterns = [
    path('', home_view, name="home_page"),
    path('register/', regiser_view, name="register"),
    path('notfound/', notfound_view, name="notfound"),
    path('addroom/', addroom_view, name="addroom"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('roomdetail/<catagory>/', roomdetail_view, name="roomdetail"),
    path('singleview/<singleuser>/', single_view, name="singleview"),
    path('roombooking/<slug>/', roombooking_view, name="roombooking"),
    path('services/', services_view, name="services"),
    path('serviceupdate/<service_id>/', serviceupdate_view, name="serviceupdate"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

from main.views import *



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('main/', include('main.urls')),
    path('chat/', include('chat.urls')),
    path('messages/', include('chatall.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Room Finder</title>
    <link rel="stylesheet" href="{% static 'css/starrr.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>

    <script  src=" https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/starrr.js' %}"></script>

  <script type="text/javascript">
    var user = '{{request.user.username}}'

          function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      const csrftoken = getCookie('csrftoken');
  </script>
  </head>
  <style >
  body{
    overflow-x: hidden;
  }
  </style>
  <body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark "><!--fixed-top-->
  <img src="{% static 'images/gb21-removebg2.png' %}" style="padding: 0 1rem 0 0;" width="35" height="35" alt="logo">
  {% if request.user.is_authenticated %}
  <a class="navbar-brand" href="{% url 'main:home_page' %}">Gebeta <span style="font:8px;">,{{request.user.username}}</span></a>
  {% else %}
  <a class="navbar-brand" href="{% url 'main:home_page' %}">Gebeta  </a>
  {% endif %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto" >
      {% block likns %}
      {% endblock likns %}
    {% if request.user.is_authenticated %}
      {% if request.user.firstname == null %}
 <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Complete Profile</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form method="post" enctype="multipart/form-data"> {% csrf_token %}
                  <div class="form-group mx-sm-3 mb-2">
                    <div class="row">
                      <div class="col">
                        <label for="exampleInputEmail1">First Name</label>
                      </div>
                      <div class="col">
                        <label for="exampleInputEmail1">Last Name</label>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col">
                        <input name="firstname" type="text" class="form-control" placeholder="First name">
                      </div>
                      <div class="col">
                        <input name="lastname" type="text" class="form-control" placeholder="Last name">
                      </div>
                    </div>
                  </div>
                  <div class="form-group mx-sm-3 mb-2">
                    <label for="exampleInputEmail1">Address</label>
                    <input name="address" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Your current address">
                    <small class="form-text text-muted">We'll never share yours Address with anyone else.</small>
                  </div>
                  <div class="form-group mx-sm-3 mb-2">
                    <label for="exampleInputPassword1">Phone Number</label>
                    <input name="phonenumber" type="phonenumber" class="form-control" id="exampleInputPassword1" placeholder="0911223344">
                  </div>
                  <div class="form-group mx-sm-3 mb-2">
                    <label for="exampleInputPassword1">Profile Picture</label><br>
                    <input  type="file" name="profile_image" class="file" accept="image/*">
                    <div class="input-group my-3">
                      <input name="profile_image" type="text" class="form-control" disabled 
                             placeholder="Upload Car Image" id="file">
                      <div class="input-group-append">
                        <button type="button" class="browse btn btn-primary">Browse...</button>
                      </div>
                    </div>
                    <div class="ml-2 col-sm-6">
                      <img src="https://placehold.it/80x80" id="preview" class="img-thumbnail">
                    </div>
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button class="btn btn-primary" type="submit" >Save changes</button>
              </div>
              </form>
            </div>
          </div>
        </div>
        <li class="nav-item" >
          <a type="button" class="nav-link" data-toggle="modal" data-target="#exampleModalCenter">Complete Your Profile</a>
        </li>
<style >
  .file {
  visibility: hidden;
  position: absolute;
}
</style>
<script type="text/javascript">
$(document).on("click", ".browse", function() {
    var file = $(this).parents().find(".file");
    file.trigger("click");
  });
  $('input[type="file"]').change(function(e) {
    var fileName = e.target.files[0].name;
    $("#file").val(fileName);

    var reader = new FileReader();
    reader.onload = function(e) {
      // get loaded data and render thumbnail.
      document.getElementById("preview").src = e.target.result;
    };
    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
  });  
</script>
      {% endif %}
    {% else %}
      {% block loglinks %}
      {% endblock loglinks %}
    {% endif %}
    <style type="text/css">
        .profile_img {
          margin-top: 10%;
          border-radius: 50%;
          width: 2rem;
          height: 2rem;
        }
    </style>
    {% if request.user.is_authenticated  %}
      <li class="nav-item dropdown ">
        
        <a href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
          <img src="{{request.user.imageURL}}" alt="sunil" class="profile_img"> 
        </a> 
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'main:register' %}">Register</a>
          <a class="dropdown-item" href="{% url 'main:services' %}">Services</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'main:logout' %}">Log out</a>
        </div>
      </li>
      {% endif %}
    </ul>

  </div>
</nav>
    {% block content %}

    
    {% endblock content %}


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/book.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/starRating.js' %}"></script>

<script type="text/javascript">
 
  if (Notification.permission != 'granted'){
    Notification.requestPermission().then(permission =>{
      console.log(permission)
    })
  }
  function showNotification(msg,msg_user){
    const notification = new Notification('New message from ' + msg_user,{
        body: msg,
        icon: "{% static 'images/b1.jpg' %}"
    });
    
    notification.onclick = (e) =>{
      
      window.location.href = "/chat/"+msg_user+"/"
     
        
    }
  }
//const msgcount = document.querySelector('#msgcount');
      {% if request.user.is_authenticated %}
      const chatSocketAll = new WebSocket(
            'ws://'
            + '127.0.0.1:8000'
            + '/ws'
            + '/chat/edu/'

        );
        
        chatSocketAll.onmessage = function(e) {
            const data = JSON.parse(e.data);
            //console.log('--'+data.message);
            //var count = msgcount.innerHTML;
            //msgcount.innerHTML = parseInt(count) + 1;
            //console.log(msgcount)
            if (Notification.permission === 'granted'){
              showNotification(data.message,data.username);
            }
        };

        chatSocketAll.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        chatSocketAll.onopen = function(e) {
              //console.log('im listening---1');
        };

      {% endif %}
  
</script>
  </body>

<div class="container-fluid pb-0 mb-0 justify-content-center text-light ">
     <footer>
         <div class="row my-5 justify-content-center py-5">
             <div class="col-11">
                 <div class="row ">
                     <div class="col-xl-8 col-md-4 col-sm-4 col-12 my-auto mx-auto a">
                         <img src="{% static 'images/gb21-removebg.png' %}" width="145" height="170" alt="logo">
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                         <h6 class="mb-3 mb-lg-4 bold-text "><b>MENU</b></h6>
                         <ul class="list-unstyled">
                             <li href="{% url 'main:home_page' %}">Home</li>
                             <li>About</li>
                             <li>Blog</li>
                             <li>Portfolio</li>
                         </ul>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                         <h6 class="mb-3 mb-lg-4 text-muted bold-text mt-sm-0 mt-5"><b>ADDRESS</b></h6>
                         <p class="mb-1">605, RATAN ICON BUILDING</p>
                         <p>SEAWOODS SECTOR</p>
                     </div>
                 </div>
                 <div class="row ">
                     <div class="col-xl-8 col-md-4 col-sm-4 col-auto my-md-0 mt-5 order-sm-1 order-3 align-self-end">
                         <p class="social text-muted mb-0 pb-0 bold-text">
                           <span class="mx-2"><i class="fa fa-facebook" aria-hidden="true"></i></span>
                           <span class="mx-2"><i class="fa fa-linkedin-square" aria-hidden="true"></i></span>
                           <span class="mx-2"><i class="fa fa-twitter" aria-hidden="true"></i></span>
                           <span class="mx-2"><i class="fa fa-instagram" aria-hidden="true"></i></span>
                         </p>
                         <small class="rights"><span>&#174;</span> Gebeta Freelance All Rights Reserved.</small>
                     </div>
                     <div class="col-xl-4 col-md-4 col-sm-4 col-auto order-1 align-self-end ">
                       <form class="form-footer my-3">
                          <input type="text"  placeholder="send us email...." name="send">
                          <input type="button" value="Go" >
                       </form>
                       <p>That's technology limitation of LCD monitors</p>
                     </div>

                 </div>
             </div>
         </div>
     </footer>
 </div>
</html>

templates/basess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Chat x Channels Rapidly</title>
    {% include 'css.html' %}
</head>
<body>

<div class='container'>
    <div class='row border-bottom my-3 py-3'>
        <div class='col'>
            <h1 class='p-0 m-0'>Chat x Channels Rapidly</h1>
        </div>
    </div>
{% block content %}
{% endblock %}
</div>


{% include 'js.html' %}
{% block script %}
{% endblock %}

</body>
</html>

templates/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

templates/home.html
{% extends "base.html" %}

{% block content %}

<p class='lead'>Welcome Home</p>
{% endblock %}

templates/js.html
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>