chat/urls.py
from django.urls import path

from . import views
from .views import ThreadView
app_name = 'chat'

urlpatterns = [
    
    path('<str:room_name>/', ThreadView.as_view(), name='room'),
]

main/urls.py
from django.urls import path
from main.views import *

from django.conf.urls.static import static
from django.conf import settings
app_name = 'main'

urlpatterns = [
    path('', home_view, name="home_page"),
    path('register/', regiser_view, name="register"),
    path('notfound/', notfound_view, name="notfound"),
    path('addroom/', addroom_view, name="addroom"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('roomdetail/<catagory>/', roomdetail_view, name="roomdetail"),
    path('singleview/<singleuser>/', single_view, name="singleview"),
    path('roombooking/<slug>/', roombooking_view, name="roombooking"),
    path('services/', services_view, name="services"),
    path('serviceupdate/<service_id>/', serviceupdate_view, name="serviceupdate"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

from main.views import *



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('main/', include('main.urls')),
    path('chat/', include('chat.urls')),
    path('messages/', include('chatall.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import *


class RegistrationForm(UserCreationForm):
	#email = forms.EmailField(max_length=60, help_text="Required. Add a valid email addess")
	class Meta:
		model = Account
		fields = ('email', 'username', 'password1', 'password2')

class AccountAuthonticationForm(forms.ModelForm):

		class Meta:
			model = Account
			fields = ('email', 'password',)

		def clean(self):
			if self.is_valid():
				email = self.cleaned_data['email']
				password = self.cleaned_data['password']
				if not authenticate(email=email, password=password):
					raise forms.ValidationError("Invalig login")

class AddRoomForm(forms.ModelForm):
	roomname = forms.CharField(max_length=60)
	class Meta:
		model = Room
		fields = ('roomname', 'roomsize', 'is_taken', 'roomimage')

class UpdateServiceForm(forms.ModelForm):
	

	class Meta:
		model = Room
		fields = ('roomimage', 'roomname', 'car_price', 'car_description', 'roomimage2', 'roomimage3', 'roomimage4')

	def save(self, commit=True):
		#if self.is_valid():
		update_room = self.instance
		
		if self.is_valid():
			update_room.roomname 		= self.cleaned_data['roomname']
			update_room.car_price 		= self.cleaned_data['car_price']
			update_room.car_description = self.cleaned_data['car_description']
			#print(self.cleaned_data['basic_price_title'])
			#catagoryid 					= self.cleaned_data['catagory']
			#catagory 					= Category.objects.get(categoryname=catagoryid)
			#update_room.catagory 		= catagory
			
				
				
			if self.cleaned_data['roomimage']:
				update_room.roomimage = self.cleaned_data['roomimage']
			if self.cleaned_data['roomimage2']:
				update_room.roomimage2 = self.cleaned_data['roomimage2']
			if self.cleaned_data['roomimage3']:
				update_room.roomimage3 = self.cleaned_data['roomimage3']
			if self.cleaned_data['roomimage4']:
				update_room.roomimage4 = self.cleaned_data['roomimage4']
			if commit:
				update_room.save()
		return update_room

		#else:
			#raise forms.ValidationError("validation error")	

class AddServiceForm(forms.ModelForm):

	class Meta:
		model = Room
		fields = ('roomname', 'car_price', 'car_description', 'roomimage', 'roomimage2', 'roomimage3', 'roomimage4')


class AddPriceBasic(forms.ModelForm):

	class Meta:
		model = Price
		fields = ('price_title', 'price_number', 'price_description', 'price_delivery', 'price_revision')

		



class CompleteUserProfileForm(forms.ModelForm):

	class Meta:
		model = Account
		fields = ('firstname', 'lastname', 'address', 'phonenumber', 'profile_image')

	def save(self, commit=True):
		user_image = self.instance
		print(self.cleaned_data['profile_image'])
		if self.is_valid():
			user_image.firstname		= self.cleaned_data['firstname']
			user_image.lastname 		= self.cleaned_data['lastname']
			user_image.address 			= self.cleaned_data['address']
			user_image.phonenumber 		= self.cleaned_data['phonenumber']
			
			print(self.cleaned_data['firstname'],self.cleaned_data['phonenumber'])
			if self.cleaned_data['profile_image']:
				user_image.profile_image = self.cleaned_data['profile_image']
			if commit:
				user_image.save()
		
		return user_image
	

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from main.forms import *
from .models import *
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.db.models import Q
from django.core.files.base import ContentFile
from django.core.files import File

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

import json
from chatall.models import Thread, ChatMessage

def get_search_query(query=None):
    queryset= []
    queries = query.split(" ")
    for q in queries:
        if q != "":
            searchs = Room.objects.filter(
                Q(catagory__categoryname__icontains=q)).distinct()
            

            for post in searchs:
                print(post)
                queryset.append(post)
    return list(set(queryset))
def get_other_users(request):
    thread = Thread.objects.all()
    other_users = []
    mythread = []
    for t in thread:
        if request.user == t.first:
            mythread.append(t)
        elif request.user == t.second:
            mythread.append(t)
    for my in mythread:
        if request.user != my.first:
            other_users.append(my.first.username)
        if request.user != my.second:
            other_users.append(my.second.username)
    if len(other_users) != 0:
        return other_users[0]
    else:
        return other_users
def home_view(request):
    #Thread.objects.get_message()
        
    context = {}
    search = request.POST.get('search')
    if search:
        #users = Room.objects.filter(catagory__categoryname=search.lower())
        #print(users)
        users = get_search_query(search)
        catagorys = Category.objects.filter(~Q(categoryname__icontains=search.lower()))

        if users:
            context = {'ids':search,'users':users,'catagorys':catagorys}
            return render(request,'main/roomdetail.html',context)

    searchRoom = Category.objects.all()

    if request.user.is_authenticated:
        form = CompleteUserProfileForm(request.POST, request.FILES,instance=request.user)
        if form.is_valid():
            form.save()
            form = CompleteUserProfileForm()
           
    useraddress = request.POST.get('firstname')
    #searchRoom = Room.objects.filter(roomname=search)
    if searchRoom:
        room_list = searchRoom
    else:
        room_list =Room.objects.all()
    paginator = Paginator(room_list,4)

    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1

    try:
        rooms = paginator.page(page)
    except(EmptyPage, InvalidPage):
        rooms = paginator.page(paginator.num_pages)

    star = request.GET.get('starRateValue')
    context['rooms'] = rooms
    #context['star'] = star
    context['useraddress'] = useraddress
    context['catagorys'] = Category.objects.all()
    context['other_users'] = get_other_users(request)



    return render(request,'main/home.html',context)




def addroom_view(request):
    rate = request.POST.get('starRate')
    item_id = request.POST.get('item_id')
    #price = AddPriceBasic()
    if rate:
        rated = False
        response_data = {}
        response_data['starRate'] = rate + " hira"
        response_data['item_id'] = "item id: " + item_id
        user = request.user
        item = Room.objects.get(id=item_id)
        ra = Rate.objects.get_or_new(user,item.roomname)
        rt = Rate.objects.all()

        #for i in ite:
            #print(i.rate_amount)
        for rat in rt:
            ratEX = Rate.objects.get_or_new(rat.user,rat.room.roomname)
            if ra == ratEX:
                rated = True
                rat.rate_amount = rate
                rat.save(update_fields=['rate_amount'])
                ite = Rate.objects.set_total(item)
                return JsonResponse(response_data)

        if rated == False :
            rateSave = Rate.objects.create()
            rateSave.user = user
            rateSave.room = item
            rateSave.rate_amount = rate
            rateSave.save()
            ite = Rate.objects.set_total(item)
            return JsonResponse(response_data)
        #print(ra)

        context['other_users'] = get_other_users(request)
    else:
        context = {}
        #form = AddRoomForm(request.POST, request.FILES)
        form = AddServiceForm(request.POST, request.FILES)
        if request.POST:
            catagory = request.POST.get('catagory')
            if catagory != 'Catagory List':
                catagorys = Category.objects.get(categoryname=catagory)
                if catagorys:
                    if form.is_valid():
                        room = form.save(commit=False)
                        room.catagory = catagorys
                        room.room_user= request.user

                        price = Price.objects.create()
                        basic_price_title = request.POST.get('basic_price_title')
                        basic_price = request.POST.get('basic_price')
                        basic_price_discription = request.POST.get('basic_price_discription')
                        basic_price_delivery = request.POST.get('basic_price_delivery')
                        
                        price.price_title = basic_price_title
                        price.price_number = basic_price
                        price.price_delivery = basic_price_delivery
                        price.price_description = basic_price_discription
                        
                        price.save()

                        pricebasic = PriceBasic.objects.create()
                        pricebasic.price = price
                        pricebasic.save()

                        pricestandard = Price.objects.create()
                        basic_price_title = request.POST.get('standard_price_title')
                        basic_price = request.POST.get('standard_price')
                        basic_price_discription = request.POST.get('standard_price_discription')
                        basic_price_delivery = request.POST.get('standard_price_delivery')
                        
                        pricestandard.price_title = basic_price_title
                        pricestandard.price_number = basic_price
                        pricestandard.price_delivery = basic_price_delivery
                        pricestandard.price_description = basic_price_discription
                        
                        pricestandard.save()

                        standard = PriceStandard.objects.create()
                        standard.price = pricestandard
                        standard.save()


                        pricepremium = Price.objects.create()
                        basic_price_title = request.POST.get('premium_price_title')
                        basic_price = request.POST.get('premium_price')
                        basic_price_discription = request.POST.get('premium_price_discription')
                        basic_price_delivery = request.POST.get('premium_price_delivery')
                        
                        pricepremium.price_title = basic_price_title
                        pricepremium.price_number = basic_price
                        pricepremium.price_delivery = basic_price_delivery
                        pricepremium.price_description = basic_price_discription
                        
                        pricepremium.save()

                        premium = PricePremium.objects.create()
                        premium.price = pricepremium
                        premium.save()

                        room.pricebasic = pricebasic 
                        room.pricepremium = premium
                        room.pricestandard = standard
                        #return redirect('main:home_page')
                        form.save()
                        form = AddServiceForm()
            else:
                context['catagory_selection_error'] = "Please Select A Catagory"
       
        context['allroom'] = form
        context['allusers'] = Account.objects.all()
        context['catagorys'] = Category.objects.all()
        context['other_users'] = get_other_users(request)
        return render(request,'main/addroom.html',context)

def regiser_view(request):
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        genderValue = request.POST.get('genderValue')
        print(genderValue) 
        if form.is_valid():
            fr = form.save(commit=False)
            if genderValue == 'Male':
                #with open('static/images/dummy-profile-image-male.png', 'rb') as f:
                    #data = f.read()
                    #print(data,genderValue)
                fr.profile_image = 'dummy-profile-image-male.png'

            elif genderValue == 'Female':
                fr.profile_image = 'dummy-profile-image-Female.jpg'  
            fr.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            if account:
                login(request, account)
                return redirect('main:home_page')
        else:
            context['registration_form'] = form
    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request,'main/register.html', context)

def login_view(request):
    context = {}
    user = request.user
    email = 'email'
    if user.is_authenticated:
        return redirect('main:home_page')
    if request.POST:

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style media="screen">

  .carousel-inner{
    height:30rem;

  }
  .carousel-caption{
    position:absolute;
    top: 54%;
    transform: translateY(60%);
    float:left!important;
    color:white;

  }

  a:hover{
    opacity: 0.7;
  }

  .lefcon{
    display: inline;
    float:left;
    width:70%;
    height:30rem;
    background:#6C9BE9;
  }
  .rightcon{
    display: inline;
    float:right;
    width:30%;
    height:30rem;
    background:#6C9BE9;
  }

  .card_image{
    width:100%;
    height:100%;
    border-radius:.4rem;
    object-fit:cover;
    object-position:top left;
  }
  .cadview:hover{
    opacity: 0.7;
  }
  .cadview{
    background:red;
    width:14rem;
    height:23rem;
    border-radius:.6rem;
  }
  .underline{
    width:9rem;
    height:.4rem;
    background-color: #292b2c;
    margin: 0 auto 3rem;
  }
  .checked{
    color:#FFD700;
    }
  .profile-img{
    width:100%;
    border-radius:50%;
  }
  .card-body{
    height:5rem;
  }
}
</style>

  <div style="padding-right:0.97rem;">
    <div class="row" style="background:#6C9BE9;height:40rem;">
    <div class="col-md-6" style="padding-left:2rem;padding-top:10rem;">
      <div class="container">
        <form  method="post"> {% csrf_token %}
        <h3 style="color:white;">Find the perfect <i>freelance</i> <br>services for your business</h3>
        <div class="input-group input-group-lg" style="padding-top:2rem;">
          <input name="search" placeholder='"Try website design"' type="text" class="form-control" aria-label="Large" aria-describedby="inputGroup-sizing-sm">
          <div class="input-group-append">
            <button class="btn btn-success" type="submit">Search</button>
          </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-6" style="padding-left:5rem;padding-top:5rem;">
      <img src="{% static 'img/india-skills.png'%}" alt="organization-skill-logo"></div>
    </div>
  </div>

      <div class="row text-center" style="background:#6C9BE9;">
        <div class="col-sm-12" style="color:white;padding-bottom:1.5rem;">
          <h1 > Popular Service </h1>
        </div>
        <div style="width:100%;">
          <div class="underline">
          </div>
        </div>
      </div>

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel"
          style="margin-bottom:3rem;background:#6C9BE9;">

      <div class="carousel-inner" >
        <div class="carousel-item active">
          <div class="row">
              {% for catagory in catagorys %}
                {% if  catagory.id >= 5 %}
                  <div class="col-md-3">
                     <a  href="{% url 'main:roomdetail' catagory=catagory %}">
                     <div class="cadview mx-auto" >
                       <img src="{{ catagory.imageURL }}" class="card_image" alt="test"  >
                       <div class="carousel-caption" style="width:10rem;max-width:10rem;">
                           <h5>{{ catagory.categoryname }}</h5>
                       </div>
                     </div>
                     </a>
                   </div>
                {% endif %}
            {% endfor %}
          </div>
          </div>
        <div class="carousel-item">
            <div class="row" >
              {% for catagory in catagorys %}
               {% if  catagory.id < 5 %}
               <div class="col-md-3">
                  <a  href="{% url 'main:roomdetail' catagory=catagory %}">
                  <div class="cadview mx-auto" >
                    <img src="{{ catagory.imageURL }}" class="card_image" alt="test"  >
                    <div class="carousel-caption" style="width:10rem;max-width:10rem;">
                        <h5>{{ catagory.categoryname }}</h5>
                    </div>
                  </div>
                  </a>
                </div>
                {% endif %}
              {% endfor %}
            </div>
        </div>
      </div>



              <a class="carousel-control-prev " href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
      </div>


      <div class="jumbotron">
        <div class="container">
          <h2 class="display-4" style="padding-bottom:1.5rem;">A whole world of freelance talent at your fingertips!!</h2>
          <i class="fa fa-check-circle-o fa-1x" aria-hidden="true">
          <span class="lead">The best for every budget</span></i>
          <p class="lead">Find high-quality services at every price point. No hourly rates, just project-based pricing.</p>
          <i class="fa fa-check-circle-o fa-1x" aria-hidden="true">
          <span class="lead">Quality work done quickly</span></i>
          <p class="lead">Find the right freelancer to begin working on your project within minutes.</p>
          <i class="fa fa-check-circle-o fa-1x" aria-hidden="true">
          <span class="lead">Protected payments, every time</span></i>
          <p class="lead">Always know what you'll pay upfront. Your payment isn't released until you approve the work.</p>
          <i class="fa fa-check-circle-o fa-1x" aria-hidden="true">
          <span class="lead">24/7 support</span></i>
          <p class="lead">Questions? Our round-the-clock support team is available to help anytime, anywhere.</p>
        </div>
      </div>


      <div class="row mx-auto">
        <div class="col-md-3">
          <div class="card mx-auto" style="width: 15rem; margin: 20px 10px;">
            <img src="{% static 'img/b3.jpg' %}" class="card-img-top" style="height: 11rem; " alt="#">
            <div class="card-body" style="box-shadow:0 0 20px 7px rgba(0,0,0,0.1);">
                <div class="row mr-auto">
                  <div class="col-md-4">
                      <img src="{% static 'img/BMW_i8_1.jpg' %}" alt="" class="profile-img">
                  </div>
                  <div class="col-md-8">
                    <strong style="font-size:.7rem;">Logo Design</strong><br>
                    <p>by hiruy</p>
                  </div>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mx-auto" style="width: 15rem; margin: 20px 10px;">
            <img src="{% static 'images/b1.jpg' %}" class="card-img-top" style="height: 11rem; " alt="#">
            <div class="card-body" style="box-shadow:0 0 20px 7px rgba(0,0,0,0.1);">
                <div class="row mr-auto">
                  <div class="col-md-4">
                      <img src="{% static 'images/BMW_i8_1.jpg' %}" alt="" class="profile-img">
                  </div>
                  <div class="col-md-8">
                    <strong style="font-size:.7rem;">Brochure Design</strong><br>
                    <p>by hiruy</p>
                  </div>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mx-auto" style="width: 15rem; margin: 20px 10px;">
            <img src="{% static 'images/b4.jpg' %}" class="card-img-top" style="height: 11rem; " alt="#">
            <div class="card-body" style="box-shadow:0 0 20px 7px rgba(0,0,0,0.1);">
                <div class="row mr-auto">
                  <div class="col-md-4">
                      <img src="{% static 'images/BMW_i8_1.jpg' %}" alt="" class="profile-img">
                  </div>
                  <div class="col-md-8">
                    <strong style="font-size:.7rem;">Illustration</strong><br>
                    <p>by hiruy</p>
                  </div>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mx-auto" style="width: 15rem; margin: 20px 10px;">
            <img src="{% static 'images/b2.jpg' %}" class="card-img-top" style="height: 11rem; " alt="#">
            <div class="card-body" style="box-shadow:0 0 20px 7px rgba(0,0,0,0.1);">
                <div class="row mr-auto">
                  <div class="col-md-4">
                      <img src="{% static 'images/BMW_i8_1.jpg' %}" alt="" class="profile-img">
                  </div>
                  <div class="col-md-8">
                    <strong style="font-size:.7rem;">Album Cover Design</strong><br>
                    <p>by hiruy</p>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>



     
               
{% endblock content %}

{% block likns %}
<li class="nav-item active">
  <a class="nav-link" href="{% url 'main:home_page' %}">Home <span class="sr-only">(current)</span></a>
</li>
{% if request.user.is_authenticated %}
  {% if request.user.firstname != null %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:addroom' %}">Add Service</a>
    </li>
  {% endif %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'chat:room' room_name=other_users %}">Message </a>
</li>
{% else %}
<li class="nav-item" >
        <a class="nav-link" href="{% url 'main:login' %}">Log in</a>
      </li>
      <li class="nav-item" >
        <a class="nav-link" href="{% url 'main:register' %}">Become a Seller</a>
      </li>
{% endif %}
{% endblock likns %}

main/templates/main/notfound.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style type="text/css">
	* {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}

body {
  padding: 0;
  margin: 0;
}

#notfound {
  position: relative;
  height: 100vh;
}

#notfound .notfound {
  position: absolute;
  left: 50%;
  top: 50%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}

.notfound {
  max-width: 767px;
  width: 100%;
  line-height: 1.4;
  padding: 0px 15px;
}

.notfound .notfound-404 {
  position: relative;
  height: 150px;
  line-height: 150px;
  margin-bottom: 25px;
}

.notfound .notfound-404 h1 {
  font-family: 'Titillium Web', sans-serif;
  font-size: 186px;
  font-weight: 900;
  margin: 0px;
  text-transform: uppercase;
  background: url('../img/text.png');
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-size: cover;
  background-position: center;
}

.notfound h2 {
  font-family: 'Titillium Web', sans-serif;
  font-size: 26px;
  font-weight: 700;
  margin: 0;
}

.notfound p {
  font-family: 'Montserrat', sans-serif;
  font-size: 14px;
  font-weight: 500;
  margin-bottom: 0px;
  text-transform: uppercase;
}

.notfound a {
  font-family: 'Titillium Web', sans-serif;
  display: inline-block;
  text-transform: uppercase;
  color: #fff;
  text-decoration: none;
  border: none;
  background: #5c91fe;
  padding: 10px 40px;
  font-size: 14px;
  font-weight: 700;
  border-radius: 1px;
  margin-top: 15px;
  -webkit-transition: 0.2s all;
  transition: 0.2s all;
}

.notfound a:hover {
  opacity: 0.8;
}

@media only screen and (max-width: 767px) {
  .notfound .notfound-404 {
    height: 110px;
    line-height: 110px;
  }
  .notfound .notfound-404 h1 {
    font-size: 120px;
  }
}

</style>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>404 HTML</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Titillium+Web:700,900" rel="stylesheet">


<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>404</h1>
			</div>
			<h2>Oops! This Page Could Not Be Found</h2>
			<p>Sorry but the page you are looking for does not exist, have been removed. name changed or is temporarily unavailable</p>
			<a href="{% url 'main:home_page' %}">Go To Homepage</a>
		</div>
	</div>

</body>
{% endblock content %}
{% block likns %}
<li class="nav-item active">
  <a class="nav-link" href="{% url 'main:home_page' %}">Home <span class="sr-only">(current)</span></a>
</li>
{% if request.user.is_authenticated %}
  {% if request.user.firstname != null %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:addroom' %}">Add Service</a>
    </li>
  {% endif %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'chat:room' room_name=other_users %}">Message </a>
</li>
{% else %}
<li class="nav-item" >
        <a class="nav-link" href="{% url 'main:login' %}">Log in</a>
      </li>
      <li class="nav-item" >
        <a class="nav-link" href="{% url 'main:register' %}">Become a Seller</a>
      </li>
{% endif %}
{% endblock likns %}

main/templates/main/services.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" media="screen" />
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="col-sm-12" >
	<div class="d-inline-flex mx-auto">
      {% for service in services %} 
        <div class="card" style="width: 18rem; margin: 20px 10px;" >
          <img src="{{service.imageURL}}" class="card-img-top" style="height: 11rem; "
          	alt="{{service.roomname}}">
          <div class="card-body" style="box-shadow:0 0 20px 7px rgba(0,0,0,0.1);">
            <h5 class="card-title">{{ service }}</h5>
            <div class="d-inline-flex justify-content-end" >
	          	<a href="{% url 'main:serviceupdate' service_id=service.id %}"><i class="fa fa-pencil " aria-hidden="true" Style="margin-right:1.0rem;">edit</i>
	          	</a>
	          	<a href=""><i class="fa fa-trash" aria-hidden="true" Style="margin-right:1.0rem;">delete</i></a>
          	</div>
          </div>

        </div>
      {% endfor %}
     </div>
</div>
{% endblock content %}

{% block likns %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'main:home_page' %}">Home <span class="sr-only">(current)</span></a>
</li>
{% if request.user.is_authenticated %}
{% if request.user.firstname != null %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'main:addroom' %}">Add Service</a>
    </li>
  {% endif %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'chat:room' room_name=other_users %}">Message </a>
</li>
{% endif %}
{% endblock likns %}